services:
  data-user:
    image: postgres:latest
    container_name: data-user
    environment:
      POSTGRES_DB: data-user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data-user:/docker-entrypoint-initdb.d
      - data-user-volume:/var/lib/postgresql/data

  data-casa:
    image: postgres:latest
    container_name: data-casa
    environment:
      POSTGRES_DB: data-casa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ./data-casa:/docker-entrypoint-initdb.d
      - data-casa-volume:/var/lib/postgresql/data

volumes:
  data-user-volume:
  data-casa-volume:
