services:

  # Base de datos de usuarios
  data-user:
    image: postgres:latest
    container_name: data-user
    environment:
      POSTGRES_DB: data-user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d casa360"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./data-user:/docker-entrypoint-initdb.d
      #- data-user:/var/lib/postgresql/data
  
  # Base de datos da aplicação
  data-casa:
    image: postgres:latest
    container_name: data-casa
    environment:
      POSTGRES_DB: data-casa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d casa360"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./data-casa:/docker-entrypoint-initdb.d
      #- data-casa:/var/lib/postgresql/data

#volumes:
#  data-user:
#  data-casa:
